In [ ]:
import pandas as pd
import numpy as np

In [3]:
data_port = pd.read_csv("portfolio_test.csv")
data_prod = pd.read_csv("product_test.csv")

In [4]:
data_port

       PRODUCT_ID PORTFOLIO_DATE  DAYS_OVER_DUE
0          919293     2025-11-25            0.0
1         1274263     2025-11-25            1.0
2         1216388     2025-11-25            0.0
3          805540     2025-11-25            0.0
4          915996     2025-11-25            0.0
...           ...            ...            ...
23705      725276     2022-04-26            1.0
23706      696473     2022-03-25            1.0
23707      681077     2022-03-25            0.0
23708      710031     2022-03-25            2.0
23709      525305     2022-01-26            0.0

[23710 rows x 3 columns]

In [5]:
data_prod

     PRODUCT_ID  TOTAL_VALUE             DELIVERY_DATE
0       1080038   468.438528  2023-11-13T06:32:50.000Z
1       1168653   792.127033  2024-02-28T18:02:22.000Z
2       1083616   925.333331  2024-04-30T20:14:56.000Z
3       1283400  2388.989747  2024-12-23T17:54:02.000Z
4        683050  2534.828414  2022-01-13T12:22:48.000Z
..          ...          ...                       ...
885      991957  1098.067087  2023-08-17T08:59:41.000Z
886     1196275  2517.768861  2024-04-17T20:40:58.000Z
887     1176495   863.932143  2024-03-11T15:24:14.000Z
888      915929  2288.836022  2023-03-01T13:13:47.000Z
889     1023497  2097.684608  2023-09-21T17:54:05.000Z

[890 rows x 3 columns]

In [ ]:
#se hace merge para tener el dataset completo
df = pd.merge(data_port, data_prod, on="PRODUCT_ID", how="inner")
df

,PRODUCT_ID,PORTFOLIO_DATE,DAYS_OVER_DUE,TOTAL_VALUE,DELIVERY_DATE
0,919293,2025-11-25,0.0,516.196111,2023-03-07T17:01:26.000Z
1,1274263,2025-11-25,1.0,2254.659982,2024-11-09T11:01:45.000Z
2,1216388,2025-11-25,0.0,980.103096,2024-06-14T20:12:16.000Z
3,805540,2025-11-25,0.0,2123.647824,2022-09-13T15:30:02.000Z
4,915996,2025-11-25,0.0,2448.941925,2023-03-01T16:55:30.000Z
...,...,...,...,...,...
23705,725276,2022-04-26,1.0,2730.018036,2022-04-19T11:36:29.000Z
23706,696473,2022-03-25,1.0,1998.544475,2022-02-08T23:03:54.000Z
23707,681077,2022-03-25,0.0,2422.384420,2022-01-08T09:15:05.000Z
23708,710031,2022-03-25,2.0,638.684711,2024-05-07T20:53:44.000Z
23709,525305,2022-01-26,0.0,967.369716,2022-01-24T08:29:35.000Z

#### Lo que me gustaría proponer para este ejercicio sería crear una variable aplicando feature engineering en base a la columna DAYS_OVER_DUE, ya que así le puedo asignar que si pasa de los 60 días de mora y llega al evento default se clasifique como 1 y si no llega se clasifique como 0. Luego se interpreta la probabilidad (ya que eso se busca medir) con metricas de evaluación

In [7]:
#creación de variable objetivo
df["target"] = (df["DAYS_OVER_DUE"] > 60).astype(int)
df

,PRODUCT_ID,PORTFOLIO_DATE,DAYS_OVER_DUE,TOTAL_VALUE,DELIVERY_DATE,target
0,919293,2025-11-25,0.0,516.196111,2023-03-07T17:01:26.000Z,0
1,1274263,2025-11-25,1.0,2254.659982,2024-11-09T11:01:45.000Z,0
2,1216388,2025-11-25,0.0,980.103096,2024-06-14T20:12:16.000Z,0
3,805540,2025-11-25,0.0,2123.647824,2022-09-13T15:30:02.000Z,0
4,915996,2025-11-25,0.0,2448.941925,2023-03-01T16:55:30.000Z,0
...,...,...,...,...,...,...
23705,725276,2022-04-26,1.0,2730.018036,2022-04-19T11:36:29.000Z,0
23706,696473,2022-03-25,1.0,1998.544475,2022-02-08T23:03:54.000Z,0
23707,681077,2022-03-25,0.0,2422.384420,2022-01-08T09:15:05.000Z,0
23708,710031,2022-03-25,2.0,638.684711,2024-05-07T20:53:44.000Z,0
23709,525305,2022-01-26,0.0,967.369716,2022-01-24T08:29:35.000Z,0

In [17]:
df["DAYS_OVER_DUE"].value_counts().sort_index()

DAYS_OVER_DUE
0.0       11096
1.0        3032
2.0        3058
3.0         162
4.0         247
          ...
910.0         1
911.0         1
933.0         2
966.0         1
1174.0        2
Name: count, Length: 457, dtype: int64

In [18]:
df["target"].value_counts()

target
0    21945
1     1765
Name: count, dtype: int64

#### Se puede observar un claro desbalance de clase por lo que el accuracy puede ser engañoso. Entonces lo que yo haría sería priorizar metricas ROC-AUC y recall

In [ ]:
df = df.drop(columns= "")